In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle

In [2]:
with open('gender_encoder.pkl', 'rb') as pkl:
    gender_encoder = pickle.load(pkl)
with open('geography_encoder.pkl', 'rb') as pkl:
    geography_encoder = pickle.load(pkl)
with open('scaler.pkl', 'rb') as pkl:
    scaler = pickle.load(pkl)
model = load_model('model.h5')

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [42]:
# Example input data
input_data = {
    'CreditScore': 600,
    'Geography': 'France',
    'Gender': 'Male',
    'Age': 40,
    'Tenure': 3,
    'Balance': 60000,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 50000
}

In [43]:
geo_encoded = geography_encoder.transform([[input_data['Geography']]]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns = geography_encoder.get_feature_names_out(['Geography']))
geo_encoded_df

d:\Prasanth\Codebase\Churn Prediction\venv\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [44]:
input_df = pd.DataFrame([input_data])
input_df = pd.concat([input_df, geo_encoded_df], axis = 1).drop(['Geography'], axis = 1)
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,Male,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [45]:
input_df['Gender'] = gender_encoder.transform(input_df['Gender'])
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [46]:
scaled_df = scaler.transform(input_df)
scaled_df

array([[-0.5169943 ,  0.90575292,  0.10132171, -0.69578059, -0.27162551,
         0.81452199,  0.6509149 ,  0.97576036, -0.86357843,  1.00615226,
        -0.58658846, -0.57283404]])

In [48]:
prediction = model.predict(scaled_df)
if prediction[0][0] > 0.5:
    print('Likely to churn')
else:
    print("Will not Churn")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
Will not Churn